# Business Intelligence Platform Configuration
# Comprehensive BI configuration for cloud-based analytics platform

platform:
  name: "Cloud BI Analytics Platform"
  version: "1.0.0"
  environment: "production"
  
# Data Sources Configuration
data_sources:
  databases:
    primary:
      type: "postgresql"
      host: "bi-platform-db.cluster-xyz.us-east-1.rds.amazonaws.com"
      port: 5432
      database: "bi_platform"
      schema: "analytics"
      
    warehouse:
      type: "redshift"
      host: "bi-platform-warehouse.abc123.us-east-1.redshift.amazonaws.com"
      port: 5439
      database: "warehouse"
      schema: "dwh"
      
  apis:
    crm_api:
      base_url: "https://api.crm-system.com/v2"
      authentication: "oauth2"
      rate_limit: 1000
      
    payment_api:
      base_url: "https://api.payment-provider.com/v1"
      authentication: "api_key"
      rate_limit: 5000
      
    marketing_api:
      base_url: "https://api.marketing-platform.com/v1"
      authentication: "bearer_token"
      rate_limit: 2000

# ML Pipeline Configuration
ml_pipeline:
  # Data Processing
  data_processing:
    batch_size: 1000
    feature_engineering:
      categorical_encoding: "one_hot"
      numerical_scaling: "standard_scaler"
      missing_value_strategy: "median"
      
  # Model Training
  training:
    algorithms:
      - "random_forest"
      - "xgboost"
      - "neural_network"
      - "linear_regression"
      
    hyperparameter_tuning:
      method: "random_search"
      n_iterations: 100
      cv_folds: 5
      
    validation:
      train_split: 0.7
      validation_split: 0.2
      test_split: 0.1
      
  # Model Deployment
  deployment:
    strategy: "blue_green"
    health_check_endpoint: "/health"
    monitoring_interval: 300
    
# Dashboard Configuration
dashboards:
  executive:
    refresh_interval: 3600  # 1 hour
    cache_duration: 1800    # 30 minutes
    widgets:
      - "revenue_kpi"
      - "customer_acquisition"
      - "churn_rate"
      - "profit_margin"
      
  operational:
    refresh_interval: 300   # 5 minutes
    cache_duration: 180     # 3 minutes
    widgets:
      - "sales_forecast"
      - "inventory_levels"
      - "order_fulfillment"
      - "customer_support"
      
  analytical:
    refresh_interval: 1800  # 30 minutes
    cache_duration: 900     # 15 minutes
    widgets:
      - "customer_segmentation"
      - "product_performance"
      - "market_analysis"
      - "predictive_models"

# Data Quality Configuration
data_quality:
  validation_rules:
    completeness:
      threshold: 0.95
      critical_fields:
        - "customer_id"
        - "transaction_date"
        - "revenue"
        
    accuracy:
      threshold: 0.98
      validation_queries:
        - "SELECT COUNT(*) FROM sales WHERE revenue < 0"
        - "SELECT COUNT(*) FROM customers WHERE email NOT LIKE '%@%'"
        
    consistency:
      cross_table_checks:
        - "orders.customer_id IN customers.customer_id"
        - "transactions.product_id IN products.product_id"
        
  monitoring:
    schedule: "0 2 * * *"  # Daily at 2 AM
    alerts:
      email: ["admin@bi-platform.com", "data-team@bi-platform.com"]
      slack_channel: "#data-quality-alerts"

# Security Configuration
security:
  authentication:
    method: "oauth2"
    provider: "active_directory"
    session_timeout: 3600
    
  authorization:
    roles:
      admin:
        permissions: ["read", "write", "delete", "admin"]
        dashboards: ["all"]
        
      analyst:
        permissions: ["read", "write"]
        dashboards: ["analytical", "operational"]
        
      viewer:
        permissions: ["read"]
        dashboards: ["executive"]
        
  data_encryption:
    at_rest: true
    in_transit: true
    algorithm: "AES-256"
    
  audit_logging:
    enabled: true
    retention_days: 365
    log_level: "info"

    # Performance Configuration
performance:
  caching:
    redis:
      host: "bi-platform-cache.abc123.cache.amazonaws.com"
      port: 6379
      ttl: 3600
      
  query_optimization:
    timeout: 300
    max_rows: 100000
    parallel_execution: true
    
  resource_limits:
    max_memory: "8GB"
    max_cpu: "4 cores"
    max_concurrent_users: 100

# Monitoring and Alerting
monitoring:
  metrics:
    system:
      - "cpu_usage"
      - "memory_usage"
      - "disk_space"
      - "network_io"
      
    application:
      - "response_time"
      - "error_rate"
      - "user_sessions"
      - "query_performance"
      
    business:
      - "daily_revenue"
      - "active_users"
      - "model_accuracy"
      - "data_freshness"
      
  alerts:
    thresholds:
      cpu_usage: 80
      memory_usage: 85
      error_rate: 5
      response_time: 2000
      
    notification_channels:
      email: "alerts@bi-platform.com"
      slack: "#bi-platform-alerts"
      pagerduty: "bi-platform-service"

# Backup and Recovery
backup:
  schedule: "0 1 * * *"  # Daily at 1 AM
  retention:
    daily: 30
    weekly: 12
    monthly: 12
    
  destinations:
    - "s3://bi-platform-backups/database/"
    - "gs://bi-platform-backups/database/"
    
recovery:
  rto: 4  # hours
  rpo: 1  # hour
  testing_schedule: "monthly"
